version: "3.2"
services:
  api:
    image: taxi-api:latest
    depends_on:
      - redis
      - model
    ports:
      - "8000:5000"
    networks:
      - shared_network

  redis:
    image: redis:6.2.6
    networks:
      - shared_network

  model:
    image: taxi-ml-service:latest
    depends_on:
      - redis
    networks:
      - shared_network

  ui:
    image: taxi-ui:latest
    environment:
      API_HOST: $API_HOST
    ports:
      - "9090:9090"
    networks:
      - shared_network

networks:
  shared_network:
    external: true